Removing state pollution in `table.rows`, removing order dependency
daknuett/ljson pull request #4
Opened 2021-08-19 03:44 UTC by sturmianseq

This PR aims to improve test reliability of test `test_unique_check` by removing state pollution in `table.rows`, as well as to remove test order dependency of `test_contains` by pre-executing `table.additem` before assertion.

The test can fail in this way by running `pip3 install pytest-repeat; python3 -m pytest --count=2 test/test_ljson_mem.py::test_unique_check`:

```
    def test_unique_check():
        import copy
        header_descriptor_ = copy.copy(header_descriptor)
        header_descriptor_["name"]["modifiers"] = ["unique"]
        header = ljson.base.generic.Header(header_descriptor_)
        table = ljson.base.mem.Table(header, data)
    
>       table.additem(item_meg)
...
    def additem(self, row):
        for k, v in row.items():
                self.header.check_data(k, v)
                if("unique" in self.header.descriptor[k]["modifiers"]):
                        # check if the value is unique
                        values = [r[k] for r in self.rows]
                        if(v in values):
>                               raise ValueError("Value {} is not unique: {}".format(k, v))
E       ValueError: Value name is not unique: meg

ljson/base/mem.py:80: ValueError
```

It may be better to clean state pollutions so that some other tests won't fail in the future due to the shared state pollution.

2021-08-19 04:32 UTC, daknuett commented
I will review this PR when I am back from my holiday in a couple of days. Thanks for contributing.

2021-08-23 16:24 UTC, daknuett commented
You are right. There is some state pollution (most notably in line 91 as you mentioned. However, it seems like your fix is rather clumsy and might lead to undefined behaviour. Note that ``data`` might be copied by the constructor.

The second change (lines 97, 100) does not seem to be necessary at all and I am not certain what its purpose is.

Also: This repository is three years old and stale. Are the changes you are submitting (to various repositories) automatically generated?

2021-08-23 16:27 UTC, daknuett commented on test/test_ljson_mem.py
> +	table.additem(item_meg)
This is not necessary. The test does not depend on this item.

2021-08-23 16:27 UTC, daknuett commented on test/test_ljson_mem.py
> +	table.rows.pop()
See above.

2021-08-23 16:29 UTC, daknuett requested changes

2021-08-23 16:29 UTC, daknuett commented on test/test_ljson_mem.py
> +	table.rows.pop()
I would instead use something like:

```suggestion
data_ = copy.copy(data)
table = Table(..., data_)
```

2021-08-24 03:41 UTC, sturmianseq commented
Thanks for the suggestion to fix the state pollution in `test_unique_check`. I've improved the test as you suggested. 

Although the state pollution can be removed by making a copy of `data` as you mentioned, the test `test_contains` fails without any changes because of the state pollution in `test_edit`, which alters "griffin" to "Griffin", making the assertion on line 98 fail. I've improved the assertion to accept "Griffin" as well as "griffin". If you prefer that I change `test_edit` to not pollute the state instead, please let me know.

The changes we are making are manually created. We are doing research on state pollution of tests by selecting popular python projects, which includes this project of yours.

2021-08-24 11:42 UTC, daknuett commented
Thanks for the changes. I will merge them. I should probably add you to some list of contributors.

Also: Do you need to cite this repository somehow? I am sure I can put together some BibTeX for that. 

However, I'd like to note that this repository is pretty stale (I wrote it 4 years ago). If you want a more active repository to cite you might want to take a look at daknuett/pyqcs. But I kinda hope you don't find any state pollution there.

All the best for your research.

2021-08-24 11:42 UTC, merged

2021-08-25 01:12 UTC, sturmianseq commented
Thanks for your time to review the PR! We are happy that you have accepted our PR. We will let you know if we need your help:)